// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Use DIRECT_URL for Prisma CLI commands (migrations, db push, etc.)
  // This must be a non-pooled connection string (without "-pooler" in hostname)
  datasource: {
    url: env("DIRECT_URL"),
  },
});
